# Global settings
shell = "fish -c '{}'"
default-scheme = "base24-solarized-dark-higher-contrast"
hooks = ["tmux source-file ~/.tmux.conf"]

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "sh \"$TINTY_THEME_FILE_PATH\" && set -gx BASE16_THEME \"$TINTY_SCHEME_ID\""
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-fzf"
path = "https://github.com/tinted-theming/tinted-fzf"
themes-dir = "fish"
