--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bryn/Pictures/Wallpapers/asian-dragon.jpg"

-- Special
background="#171517"
foreground="#c5c4c5"
cursor="#c5c4c5"

-- Colors
color0="#171517"
color1="#771537"
color2="#992555"
color3="#ba1e45"
color4="#d02b5b"
color5="#e4567d"
color6="#df76a8"
color7="#c5c4c5"
color8="#514f51"
color9="#771537"
color10="#992555"
color11="#ba1e45"
color12="#d02b5b"
color13="#e4567d"
color14="#df76a8"
color15="#c5c4c5"
