# Shell variables
# Generated by 'wal'
wallpaper='/home/bryn/Pictures/Wallpapers/asian-dragon.jpg'

# Special
background='#171517'
foreground='#c5c4c5'
cursor='#c5c4c5'

# Colors
color0='#171517'
color1='#771537'
color2='#992555'
color3='#ba1e45'
color4='#d02b5b'
color5='#e4567d'
color6='#df76a8'
color7='#c5c4c5'
color8='#514f51'
color9='#771537'
color10='#992555'
color11='#ba1e45'
color12='#d02b5b'
color13='#e4567d'
color14='#df76a8'
color15='#c5c4c5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
